"""create cart table

Revision ID: 036f1feec294
Revises: 63dcbcc2c872
Create Date: 2026-05-17 10:40:23.685117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '036f1feec294'
down_revision: Union[str, Sequence[str], None] = '63dcbcc2c872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('cart', 'user_id',
               existing_type=mysql.CHAR(length=36),
               nullable=False)
    op.alter_column('cart', 'menu_item_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('cart_ibfk_1'), 'cart', type_='foreignkey')
    op.drop_constraint(op.f('cart_ibfk_2'), 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'menu_items', ['menu_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cart', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key(op.f('cart_ibfk_2'), 'cart', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('cart_ibfk_1'), 'cart', 'menu_items', ['menu_item_id'], ['id'])
    op.alter_column('cart', 'menu_item_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('cart', 'user_id',
               existing_type=mysql.CHAR(length=36),
               nullable=True)
    op.drop_column('cart', 'created_at')
    # ### end Alembic commands ###
