"""update settings model

Revision ID: 295771882104
Revises: a75e1b4dd9cd
Create Date: 2026-03-25 10:21:56.026833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295771882104'
down_revision: Union[str, Sequence[str], None] = 'a75e1b4dd9cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurantId', sa.Integer(), nullable=False),
    sa.Column('acceptingOrders', sa.Boolean(), nullable=True),
    sa.Column('busyMode', sa.Boolean(), nullable=True),
    sa.Column('prepTime', sa.Integer(), nullable=True),
    sa.Column('openTime', sa.String(length=20), nullable=True),
    sa.Column('closeTime', sa.String(length=20), nullable=True),
    sa.Column('orderAlert', sa.Boolean(), nullable=True),
    sa.Column('ringtone', sa.String(length=50), nullable=True),
    sa.Column('notificationInterval', sa.String(length=50), nullable=True),
    sa.Column('autoAccept', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['restaurantId'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_settings_id'), 'restaurant_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_settings_id'), table_name='restaurant_settings')
    op.drop_table('restaurant_settings')
    # ### end Alembic commands ###
