"""table booking settings

Revision ID: 2f2b8aca391e
Revises: 4cc3c888df18
Create Date: 2026-05-25 01:38:17.822887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2b8aca391e'
down_revision: Union[str, Sequence[str], None] = '4cc3c888df18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blackout_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blackout_dates_id'), 'blackout_dates', ['id'], unique=False)
    op.create_table('table_booking_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('accept_bookings', sa.Boolean(), nullable=True),
    sa.Column('booking_mode', sa.String(length=50), nullable=True),
    sa.Column('booking_notifications', sa.Boolean(), nullable=True),
    sa.Column('booking_start_time', sa.String(length=20), nullable=True),
    sa.Column('booking_end_time', sa.String(length=20), nullable=True),
    sa.Column('slot_duration', sa.Integer(), nullable=True),
    sa.Column('total_tables', sa.Integer(), nullable=True),
    sa.Column('max_guests_per_table', sa.Integer(), nullable=True),
    sa.Column('parallel_bookings', sa.Integer(), nullable=True),
    sa.Column('advance_payment_enabled', sa.Boolean(), nullable=True),
    sa.Column('advance_payment_type', sa.String(length=20), nullable=True),
    sa.Column('advance_payment_value', sa.Integer(), nullable=True),
    sa.Column('waitlist_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_promote_waitlist', sa.Boolean(), nullable=True),
    sa.Column('waitlist_notifications', sa.Boolean(), nullable=True),
    sa.Column('max_waitlist_size', sa.Integer(), nullable=True),
    sa.Column('auto_assign_tables', sa.Boolean(), nullable=True),
    sa.Column('smart_capacity_matching', sa.Boolean(), nullable=True),
    sa.Column('merge_tables', sa.Boolean(), nullable=True),
    sa.Column('vip_table_priority', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    op.create_index(op.f('ix_table_booking_settings_id'), 'table_booking_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_booking_settings_id'), table_name='table_booking_settings')
    op.drop_table('table_booking_settings')
    op.drop_index(op.f('ix_blackout_dates_id'), table_name='blackout_dates')
    op.drop_table('blackout_dates')
    # ### end Alembic commands ###
