"""update in menu_items

Revision ID: 3fef9e55c04f
Revises: 233fba69f574
Create Date: 2026-03-24 14:48:02.807102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3fef9e55c04f'
down_revision: Union[str, Sequence[str], None] = '233fba69f574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('menu_items', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('menu_items', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('menu_items', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('menu_items', 'description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('menu_items', 'price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('menu_items', 'image_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu_items', 'image_url',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('menu_items', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('menu_items', 'description',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('menu_items', 'name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('menu_items', 'updated_at')
    op.drop_column('menu_items', 'created_at')
    op.drop_column('menu_items', 'is_deleted')
    # ### end Alembic commands ###
