"""table booking settings

Revision ID: 4cc3c888df18
Revises: 036f1feec294
Create Date: 2026-05-25 01:33:09.231621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc3c888df18'
down_revision: Union[str, Sequence[str], None] = '036f1feec294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_table_bookings_id'), 'table_bookings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_bookings_id'), table_name='table_bookings')
    # ### end Alembic commands ###
