"""add restaurant extra fields

Revision ID: 9a0e064e4b9e
Revises: ea8269d8da33
Create Date: 2026-05-08 12:12:57.982416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a0e064e4b9e'
down_revision: Union[str, Sequence[str], None] = 'ea8269d8da33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('cuisine', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('rating', sa.String(length=10), nullable=True))
    op.add_column('restaurants', sa.Column('time', sa.String(length=30), nullable=True))
    op.add_column('restaurants', sa.Column('table_available', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'table_available')
    op.drop_column('restaurants', 'time')
    op.drop_column('restaurants', 'rating')
    op.drop_column('restaurants', 'category')
    op.drop_column('restaurants', 'cuisine')
    # ### end Alembic commands ###
