"""add city and pincode

Revision ID: ea8269d8da33
Revises: 7d4a6eda4842
Create Date: 2026-05-07 15:26:35.610560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8269d8da33'
down_revision: Union[str, Sequence[str], None] = '7d4a6eda4842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('addresses', sa.Column('pincode', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'pincode')
    op.drop_column('addresses', 'city')
    # ### end Alembic commands ###
